services:
  app:
    build: .
    image: app
    container_name: app
    ports:
      - "${APP_PORT}:8000"
    env_file:
      - .env
    depends_on:
      - db
      - redis
    volumes:
      - ./src:/app/src
  db:
    image: postgres:17-alpine
    container_name: db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "${DB_EXPOSED_PORT}:${DB_PORT}"
  redis:
    image: redis:8-alpine
    container_name: redis
    ports:
      - "${REDIS_EXPOSED_PORT}:${REDIS_PORT}"
volumes:
  postgres_data:
